In [1]:
import pandas as pd
import numpy as np 
from matplotlib import pyplot as plt

In [4]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [14]:
data = pd.read_csv('sample.csv')

In [15]:
data.isnull().sum()

gender                                  0
marital_status                          0
region                                  0
highest_education                       0
school                                  0
graduation                              0
study_programme                         0
employment_status                       0
last_year_benefitted                    0
loan_purpose                            0
repayment_status                        0
repayment_info_source                   0
repayment_method                        0
repayment_method_convenience            0
effectiveness_repayment_method          0
collection_strategy_effectiveness       0
interaction_quality_on_repayment        0
alternative_collection_strategies       0
overall_experience_with_loan_process    0
age_group                               0
over_under_milion                       0
dtype: int64

In [16]:
data.sample(10)

,gender,marital_status,region,highest_education,school,graduation,study_programme,employment_status,last_year_benefitted,loan_purpose,repayment_status,repayment_info_source,repayment_method,repayment_method_convenience,effectiveness_repayment_method,collection_strategy_effectiveness,interaction_quality_on_repayment,alternative_collection_strategies,overall_experience_with_loan_process,age_group,over_under_milion
52,female,divorced,southern,master,chanco,2002.0,cultural_studies,self_employed,2001,tuition_living_stationery,fully_paid,inperson_employer,monthly_salary,very_convenient,very_effective,very_effective,positive,work with borrowers to find matually beneficia...,very satisfied,49 - 59,under
216,female,widowed,central,master,mzuni,2016.0,human_resource_development_,employed_fulltime,2015,tuition_living_stationery,fully_paid,none,monthly_salary,very_convenient,effective,very_effective,neutral,use of automated system linked to banks accounts,satisfied,49 - 59,over
307,female,married,southern,bachelor,mzuni,2011.0,mbbs,employed_fulltime,2010,tuition_living,partially_paid,inperson,voluntary_monthly,inconvenient,ineffective,effective,positive,automate the system,neutral,28 - 37,over
185,female,single,southern,bachelor,mzuni,2015.0,education_science,unemployed,2014,tuition_living,not_paid,inperson,none,inconvenient,ineffective,neutral,neutral,automate the system,neutral,49 - 59,over
283,female,married,central,master,com,2016.0,mbbs,employed_fulltime,2015,tuition_living,partially_paid,email_inperson,monthly_salary,very_convenient,very_effective,very_effective,very_positive,automate the system,very satisfied,38 - 48,over
218,male,married,southern,bachelor,poly,2004.0,electrical_engineering,employed_fulltime,2003,tuition,fully_paid,employer,oneoff,neutral,effective,effective,neutral,enhanced corporate relationship.,neutral,38 - 48,under
161,male,divorced,northern,doctorate,chanco,2009.0,education_science,employed_fulltime,2008,living,fully_paid,phonecall,monthly_salary,neutral,effective,effective,positive,automate the system,satisfied,38 - 48,under
10,male,single,northern,bachelor,poly,2015.0,accountancy,employed_fulltime,2014,tuition_living,not_paid,email,none,inconvenient,ineffective,neutral,neutral,accountability_reporting,neutral,21 - 27,over
166,male,widowed,central,doctorate,chanco,2005.0,education_science,employed_fulltime,2003,tuition_living,fully_paid,inperson,monthly_salary,convenient,effective,effective,positive,improve on communication strategies,satisfied,49 - 59,under
247,male,single,central,master,mzuni,2014.0,information_and_communication_technology,employed_fulltime,2013,tuition_living_stationery,not_paid,none,none,inconvenient,ineffective,neutral,neutral,political will to sustain heslgb is vital for ...,neutral,38 - 48,over

In [ ]:
# attempted feature extraction
from tsfresh import extract_features

# Sample time series data with an id column
df['id'] = 1
df['time'] = range(len(df))

# Extract features using tsfresh
extracted_features = extract_features(df, column_id='id', column_sort='time')

print(extracted_features)